## Values for Falcosidekick Helm chart
## Install: helm install falcosidekick falcosecurity/falcosidekick -n security-monitoring -f falcosidekick.yaml

replicaCount: 1

config:
  webhook:
    address: ""
    minimumpriority: "warning"

  prometheus:
    extralabels: ""

webui:
  enabled: false

resources:
  limits:
    memory: 128Mi
    cpu: 100m
  requests:
    memory: 64Mi
    cpu: 50m

service:
  type: ClusterIP
  port: 2801

prometheus:
  serviceMonitor:
    enabled: true
    additionalLabels: {}
    interval: 30s
    scrapeTimeout: 10s
