apiVersion: v1
kind: ServiceAccount
metadata:
  name: security-operator
  namespace: security-monitoring
  labels:
    app: security-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-operator
  namespace: applications
  labels:
    app: app-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: auditor
  namespace: default
  labels:
    app: auditor
